version: '3'

services:
  provider:
   image: fint/provider:latest
   ports:
     - "8600:8080"
   environment:
    TZ: Europe/Oslo
    springfox.title: "Play-With-FINT-Adapter Provider"
    fint.events.orgIds: "pwfa.no"
    fint.events.component: pwfa
    fint.events.env: pwfa
    fint.events.redisson.addresses: "redis://redis:6379"
    fint.audit.mongo.hostname: ucp.rogfk.no
    fint.audit.mongo.databasename: fint-audit-pwfa
   deploy:
    replicas: 1
    restart_policy:
     condition: on-failure
     delay: 5s
     max_attempts: 3
     window: 120s
   depends_on:
    - redis

  consumer:
   image: fint/pwfa-consumer:latest
   ports:
     - "8601:8080"
   environment:
    TZ: Europe/Oslo
    server.context-path: /
    springfox.title: "Play-With-FINT-Adapter Consumer"
    fint.events.orgIds: "pwfa.no"
    fint.events.component: pwfa
    fint.events.env: pwfa
    fint.events.redisson.addresses: "redis://redis:6379"
    fint.audit.mongo.hostname: ucp.rogfk.no
    fint.audit.mongo.databasename: fint-audit-pwfa
   deploy:
    replicas: 1
    restart_policy:
     condition: on-failure
     delay: 5s
     max_attempts: 3
     window: 120s
   depends_on:
    - redis
    - provider

  redis:
    image: redis:3.2.8-alpine
    environment:
      TZ: Europe/Oslo
    deploy:
     replicas: 1
     restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 120s